### PR TITLE
Fix error caused by updating immutable object

### LINKED ISSUE #137: TypeError: Cannot set property graph of #<Quad> which has only a getter
I am trying to deploy ldf-server in my shared hosting using the latest version of the package. After executed ldf-server config.json everything is ok, but after the first request to the server, the process exit and throw the following error:
```
@ldf/core/lib/datasources/Datasource.js:150
      quad.graph = quad.graph && quad.graph.termType !== 'DefaultGraph' ? quad.graph : (graph || quad.graph);
                 ^
TypeError: Cannot set property graph of #<Quad> which has only a getter
    at SimpleTransformIterator._map
```
To reproduce the error:

You can reproduce the problem by trying the following.
1.  `npm install -g @ldf/server`
2. `ldf-server config.json`

Here my config.json file:
```
{
  "@context": "https://linkedsoftwaredependencies.org/bundles/npm/@ldf/server/^3.0.0/components/context.jsonld",
  "@id": "urn:ldf-server:my",
  "import": "preset-qpf:config-defaults.json",

  "title": "Linked Data Fragments server",
  "port": 30000,
  "workers": 1,
  "protocol": "http",

  "datasources": [
    {
      "@id": "ex:linkedDlsource",
      "@type": "HdtDatasource",
      "datasourceTitle": "LinkedDL 2021",
      "description": "Short description here",
      "datasourcePath": "linkeddl",
      "hdtFile": "data/raw-data.hdt"
    }
 ]
}
```
*Note:* I downloaded the source code from github.com and installed it. Everything works as expected. Same HDT file and config file. For some reason, compiling from source code works fine, but from the npm registry doesn't.

### PR DESCRIPTION
**Pull request by Dexagod**
I fixed the updates to the immutable `Quad` object in the `Datasource.js` file by creating a new `Quad` object with the updated value.
I updated the tests for the `CompositeDatasource` to include a `dataFactory` field for the created datasources.
This closes #137

### CODE REVIEW

File: packages/core/lib/datasources/Datasource.js [hunk 1]
```diff
@@ -137,18 +137,25 @@ class Datasource extends EventEmitter {
...
+      else if (graph && (!quad.graph || quad.graph.termType === 'DefaultGraph'))
+        transformedGraph = graph;
+
+      const transformedQuad = this.dataFactory.quad(
+        transformedSubject || quad.subject,
+        quad.predicate,
+        transformedObject || quad.object,
+        transformedGraph || quad.graph,
+      );
+      return transformedQuad;
```
Comment (RubenVerborgh) [inline packages/core/lib/datasources/Datasource.js:158]:
```suggestion
      return this.dataFactory.quad(
        transformedSubject || quad.subject,
        quad.predicate,
        transformedObject || quad.object,
        transformedGraph || quad.graph,
      );
```

File: packages/core/lib/datasources/Datasource.js [hunk 2]
```diff
@@ -137,18 +137,25 @@ class Datasource extends EventEmitter {
     // Transform the received quads
     let destination = new BufferedIterator(), outputQuads, graph = this._graph;
     outputQuads = destination.map((quad) => {
+      let transformedSubject, transformedObject, transformedGraph;
```
Comment (RubenVerborgh) [inline packages/core/lib/datasources/Datasource.js:140]: Alternative way of writing the method could be to

```suggestion
      let { subject, predicate, object, graph } = quad;
```

so you don't have to use `quad.` all the time below, and the `\\` from the `transformedQuad` can also be dropped.

**Review by RubenVerborgh — APPROVED** [review]
Good work!

File: packages/core/lib/datasources/Datasource.js [hunk 3]
```diff
@@ -137,18 +137,25 @@ class Datasource extends EventEmitter {
...
       // Translate blank nodes in the result to blank node IRIs.
       if (quad.subject && quad.subject.termType === 'BlankNode' && !this._skolemizeBlacklist[quad.subject.value])
         quad.subject = this.dataFactory.namedNode(blankNodePrefix + quad.subject.value);
```
Comment (rubensworks) [inline packages/core/lib/datasources/Datasource.js:143]: This will still produce an error.

File: packages/core/lib/datasources/Datasource.js [hunk 4]
```diff
@@ -137,18 +137,25 @@ class Datasource extends EventEmitter {
...
       if (quad.object  && quad.object.termType  === 'BlankNode' && !this._skolemizeBlacklist[quad.object.value])
         quad.object  = this.dataFactory.namedNode(blankNodePrefix + quad.object.value);
```
Comment (rubensworks) [inline packages/core/lib/datasources/Datasource.js:145]: Same as above.

**Review by rubensworks — CHANGES_REQUESTED** [review]
You may also want to consider updating the lib (I assume N3.js) that provides the data factory.
Then you can effectively confirm that #137 is fixed.

File: packages/core/lib/datasources/Datasource.js (hunk 2 above)
Comment (Dexagod) [reply packages/core/lib/datasources/Datasource.js:140]: It is indeed not the most elegant solution, but a graph variable was already declared for that function, and I wanted to make sure not to introduce inconsistencies or make the code difficult to understand. 
I could update it, and rename the previously introduced graph variable (that one refers to the default graph that has been set if I recall correctly)

File: packages/core/lib/datasources/Datasource.js (hunk 3 above)
Comment (Dexagod) [reply packages/core/lib/datasources/Datasource.js]: Updated the subject and object assignments too.
Any other way this produces an error

File: packages/core/lib/datasources/Datasource.js (hunk 1 above)
Comment (Dexagod) [reply packages/core/lib/datasources/Datasource.js:158]: Is this an indentation issue?

Comment (rubensworks) [reply packages/core/lib/datasources/Datasource.js:158]: No need to have `transformedQuad`.

File: packages/core/lib/views/RdfView.js [hunk 5]
```diff
@@ -86,8 +86,9 @@ class RdfView extends View {
           metadataGraph = settings.metadataGraph;
           writer.addQuad(dataFactory.namedNode(metadataGraph), dataFactory.namedNode(primaryTopic), dataFactory.namedNode(settings.fragmentUrl), dataFactory.namedNode(metadataGraph));
         }
-        quad.graph = quad.graph.termType === 'DefaultGraph' ? (metadataGraph ? dataFactory.namedNode(metadataGraph) : dataFactory.defaultGraph()) : quad.graph;
-        writer.addQuad(quad);
+        const graph = quad.graph.termType === 'DefaultGraph' ? (metadataGraph ? dataFactory.namedNode(metadataGraph) : dataFactory.defaultGraph()) : quad.graph;
+        const newQuad = dataFactory.quad(quad.subject, quad.predicate, quad.object, graph);
```
Comment (rubensworks) [inline packages/core/lib/views/RdfView.js:90]: No need to have `newQuad`. (also below)

File: packages/core/lib/datasources/Datasource.js (hunk 3 above)
Comment (rubensworks) [reply packages/core/lib/datasources/Datasource.js]: If it runs and the tests pass with the latest N3 version, then it should be ok I guess.

File: packages/core/lib/datasources/Datasource.js (hunk 1 above)
Comment (Dexagod) [reply packages/core/lib/datasources/Datasource.js:158]: :sweat_smile:

File: packages/core/lib/datasources/Datasource.js (hunk 2 above)
Comment (Dexagod) [reply packages/core/lib/datasources/Datasource.js]: I changed the custom default graph variable to _defaultGraph_ instead of _graph_, and used this approach in latest commit

**Comment by Dexagod** [comment]
I have addressed all issues and updated the N3 library and the relevant tests, but it seems that the last commit reduced the test coverage with .04%, not sure why

**Comment by rubensworks** [comment]
Thanks, great work!
